# Getting Started
First, we import `torch`. Please note that although it is known as PyTorch, the code uses `torch` rather than `pytorch`. Here we use d2l package directly.

In [11]:
from d2l import torch as d2l

A tensor represents an array of numerical values, which may have multiple dimensions. A tensor with one axis corresponds to a mathematical vector;
a tensor with two axes corresponds to a mathematical matrix; tensors with more than two axes have no specific mathematical name.<br><br>
First, we can use `arange` to create a row vector `x`. This row vector contains the first 12 integers starting from 0; by default, these are created as integers.It is also possible to specify that they be created as floating-point numbers. Each value in a tensor is referred to as an element. For example, the tensor `x` has 12
elements. Unless otherwise specified, new tensors will be stored in memory and computed using CPU-based calculations.

In [12]:
x = d2l.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

You can access the shape of a tensor (its dimensions along each axis) via its `shape` attribute.

In [13]:
x.shape

torch.Size([12])

If you simply wish to know the total number of elements in a tensor—that is, the product of all elements in its shape—you can check its size. Since we are dealing with
a vector here, its shape is the same as its size.

In [14]:
x.numel()

12

To change the shape of a tensor without altering the number or values of its elements, you can call the `reshape` function. For example, you can convert the tensor `x` from a row vector of shape
(12,) into a matrix of shape (3,4). This new tensor contains the same values as before the conversion, but it is treated as a matrix with 3 rows and 4 columns
. It is important to emphasise that, although the shape of the tensor has changed, its element values remain unchanged. Note that changing the shape of a tensor
does not alter its size.

In [23]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

We do not need to change the shape by manually specifying each dimension. In other words, if our target shape is (height, width), then once
the width is known, the height is automatically calculated; we do not need to perform the division ourselves. In the example above, to obtain a matrix with 3 rows,
we manually specified that it has 3 rows and 4 columns. Fortunately, we can utilize this automatic dimension calculation feature by using -1. In other words, we can
use `x.reshape(-1, 4)` or `x.reshape(3, -1)` instead of `x.reshape(3, 4)`.<br><br>
Sometimes, we wish to initialize a matrix using all zeros, all ones, other constants, or numbers sampled at random from a specific distribution. We can create
a tensor of shape (2, 3, 4) in which all elements are set to 0. The code is as follows:

In [17]:
d2l.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Similarly, we can create a tensor of shape (2, 3, 4) in which all elements are set to 1. The code is as follows:

In [18]:
d2l.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Sometimes we wish to obtain the values of each element in a tensor by randomly sampling from a specific probability distribution. For example, when we construct arrays to serve
as parameters in a neural network, we usually initialize the parameter values randomly. The following code creates a tensor of shape (3, 4), in which
each element is randomly sampled from a standard Gaussian distribution (normal distribution) with a mean of 0 and a standard deviation of 1.

In [21]:
d2l.randn(3, 4)

tensor([[ 0.6853, -1.4689, -0.9566,  0.6809],
        [ 0.4508, -1.4430, -1.0428, -0.0424],
        [ 0.0448,  1.8010,  0.4397,  0.6816]])

We can also assign specific values to each element of the desired tensor by providing a Python list (or nested list) containing numerical values. Here,
the outermost list corresponds to axis 0, whilst the inner lists correspond to axis 1.

In [22]:
d2l.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])