# **2.3 Linear Algebra**
This section will introduce the fundamental mathematical objects, arithmetic and operations in linear algebra, and represent them using mathematical notation and
the corresponding code implementations.
## **2.3.1 Scalar**
**Strictly speaking, a value consisting of a single numerical quantity is called a scalar.** <br><br>
This book employs mathematical notation, in which scalar variables are denoted by ordinary lower-case letters (e.g. x, y and z). **In this book, $\mathbb{R}$ denotes the set of all (continuous) real
scalars.** We shall define the concept of a ‘space’ strictly later on, but for now it is sufficient to remember that the expression x ∈ $\mathbb{R}$ is the formal way of stating that x is a real-valued scalar.
The symbol ∈ is called ‘belongs to’ and denotes ‘being a member of a set’. For example, x, y ∈ {0, 1} can be used to indicate that x and y are numbers whose values can only
be 0 or 1.<br><br>
**A scalar is represented by a tensor with only one element.**

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## **2.3.2 Vector**
**A vector can be regarded as a list of scalar values. These scalar values are referred to as the elements or components of the vector.** In mathematical notation, vectors are usually denoted by bold, lower-case letters (e.g.
**x**, **y** and **z**).<br><br>
**Vectors are represented using one-dimensional tensors.** Generally speaking, tensors can be of any length, depending on the machine’s memory limitations.

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

A great deal of literature considers **the column vector to be the default direction of a vector, and this is also the case in this book.** In mathematics, a vector x can
be written as:<br>
##### **(2.3.1)**
![Default representation of vectors](../images/picture2_3_1.png)<br>
Here, $x_1$, …, $x_n$ are the elements of the vector. **In the code, we access any element via the tensor’s indices.**

In [3]:
x[3]

tensor(3)

### **Length, Dimensions and Shape**
In mathematical notation, if we wish to
**state that a vector x consists of n real-valued scalars, we can represent it as x ∈ R^n. The length of a vector is commonly referred to as its dimension.**<br><br>
As with ordinary Python arrays, **we can access the length of a tensor by calling Python’s built-in len() function**.

In [4]:
len(x)

4

When representing a vector (with only one axis) as a tensor, we can also access the vector’s length via the .shape attribute. **The shape is a
list of elements that specifies the length (dimension) of the tensor along each axis. For a tensor with only one axis, the shape consists of a single element.**

In [5]:
x.shape

torch.Size([4])

Please note that the term ‘dimension’ often has different meanings in different contexts. Let us clarify this here: **the dimension of a vector or axis is used to denote the length of the vector or axis, that is, the number of elements in the vector or axis. However, the
dimension of a tensor is used to denote the number of axes it possesses. In this sense, the dimension of a particular axis of a tensor is the length of that axis.**
## **2.3.3 Matrix**
Matrices are usually denoted by bold, capital letters
(e.g. **X**, **Y** and **Z**) and are represented in code as tensors with two axes.<br><br>
In mathematical notation, a matrix **A** is denoted as **A** ∈ $\mathbb{R}^{m×n}$, consisting of m rows and n columns of real scalars. We may regard any matrix **A** ∈ $\mathbb{R}^{m×n}$ as
a table, in which each element $a_{ij}$ belongs to the i-th row and the j-th column:<br>
##### **(2.3.2)**
![Standard representation of a matrix](../images/picture2_3_2.png)<br>
For any **A** ∈ $\mathbb{R}^{m×n}$, the shape of **A** is (m, n) or m×n. When a matrix has the same number of rows and columns, its shape becomes square;
therefore, it is called a square matrix.

In [6]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

We can access the scalar element $a_{ij}$ in a matrix using a row index ($i$) and a column index ($j$), for example $[A]_{ij}$. If the scalar
element of matrix **A** is not specified, as in [(2.3.2)](#232), we can simply use the lowercase letter indices aij of matrix $A$ to refer to $[A]_{ij}$.<br><br>
**When we swap the rows and columns of a matrix, the result is called the transpose of the matrix.** The transpose of a matrix is usually denoted by $A^{\mathrm{T}}$; if $B$ = $A^{\mathrm{T}}$,
then for any $i$ and $j$, $b_{ij}$ = $a_{ji}$. Therefore, the transpose in [(2.3.2)](#232) is an n × m matrix:<br>
##### **(2.3.3)**
![Transpose matrix representation](../images/picture2_3_3.png)<br>

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

As a special type of matrix, a symmetric matrix $A$ is equal to its transpose: $A$ = $A^{\mathrm{T}}$. Here, we define a symmetric matrix $B$:

In [13]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

## **2.3.4 Tensor**
A tensor (in this subsection,
the term ‘tensor’ refers to an algebraic object) is a generalized way of describing an n-dimensional array with an arbitrary number of axes.

In [14]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## **2.3.5 Basic Properties of Tensor Algorithms**
Scalars, vectors, matrices and tensors with any number of axes (the term ‘tensor’ in this subsection refers to algebraic objects) possess a number of practical properties. For example, from the definition of
element-wise operations, it can be seen that **any unary element-wise operation does not alter the shape of its operands. Similarly, given any two tensors of the same
shape, the result of any binary element-wise operation will be a tensor of the same shape**. For example, adding two matrices of the same shape
involves performing element-wise addition on these two matrices.