# **2.3 Linear Algebra**
This section will introduce the fundamental mathematical objects, arithmetic and operations in linear algebra, and represent them using mathematical notation and
the corresponding code implementations.
## **2.3.1 Scalar**
**Strictly speaking, a value consisting of a single numerical quantity is called a scalar.** <br><br>
This book employs mathematical notation, in which scalar variables are denoted by ordinary lower-case letters (e.g. x, y and z). **In this book, $\mathbb{R}$ denotes the set of all (continuous) real
scalars.** We shall define the concept of a ‘space’ strictly later on, but for now it is sufficient to remember that the expression x ∈ $\mathbb{R}$ is the formal way of stating that x is a real-valued scalar.
The symbol ∈ is called ‘belongs to’ and denotes ‘being a member of a set’. For example, x, y ∈ {0, 1} can be used to indicate that x and y are numbers whose values can only
be 0 or 1.<br><br>
**A scalar is represented by a tensor with only one element.**

In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## **2.3.2 Vector**
**A vector can be regarded as a list of scalar values. These scalar values are referred to as the elements or components of the vector.** In mathematical notation, vectors are usually denoted by bold, lower-case letters (e.g.
**x**, **y** and **z**).<br><br>
**Vectors are represented using one-dimensional tensors.** Generally speaking, tensors can be of any length, depending on the machine’s memory limitations.

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

A great deal of literature considers **the column vector to be the default direction of a vector, and this is also the case in this book.** In mathematics, a vector x can
be written as:<br>
##### **(2.3.1)**
![Default representation of vectors](../images/picture2_3_1.png)<br>
Here, $x_1$, …, $x_n$ are the elements of the vector. **In the code, we access any element via the tensor’s indices.**

In [4]:
x[3]

tensor(3)

### **Length, Dimensions and Shape**
In mathematical notation, if we wish to
**state that a vector x consists of n real-valued scalars, we can represent it as x ∈ R^n. The length of a vector is commonly referred to as its dimension.**<br><br>
As with ordinary Python arrays, **we can access the length of a tensor by calling Python’s built-in len() function**.

In [5]:
len(x)

4

When representing a vector (with only one axis) as a tensor, we can also access the vector’s length via the .shape attribute. **The shape is a
list of elements that specifies the length (dimension) of the tensor along each axis. For a tensor with only one axis, the shape consists of a single element.**

In [6]:
x.shape

torch.Size([4])

Please note that the term ‘dimension’ often has different meanings in different contexts. Let us clarify this here: **the dimension of a vector or axis is used to denote the length of the vector or axis, that is, the number of elements in the vector or axis. However, the
dimension of a tensor is used to denote the number of axes it possesses. In this sense, the dimension of a particular axis of a tensor is the length of that axis.**
## **2.3.3 Matrix**
Matrices are usually denoted by bold, capital letters
(e.g. **X**, **Y** and **Z**) and are represented in code as tensors with two axes.<br><br>
In mathematical notation, a matrix **A** is denoted as **A** ∈ $\mathbb{R}^{m×n}$, consisting of m rows and n columns of real scalars. We may regard any matrix **A** ∈ $\mathbb{R}^{m×n}$ as
a table, in which each element $a_{ij}$ belongs to the i-th row and the j-th column:<br>
##### **(2.3.2)**
![Standard representation of a matrix](../images/picture2_3_2.png)<br>
For any **A** ∈ $\mathbb{R}^{m×n}$, the shape of **A** is (m, n) or m×n. When a matrix has the same number of rows and columns, its shape becomes square;
therefore, it is called a square matrix.

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

We can access the scalar element $a_{ij}$ in a matrix using a row index ($i$) and a column index ($j$), for example $[A]_{ij}$. If the scalar
element of matrix **A** is not specified, as in [(2.3.2)](#232), we can simply use the lowercase letter indices aij of matrix $A$ to refer to $[A]_{ij}$.<br><br>
**When we swap the rows and columns of a matrix, the result is called the transpose of the matrix.** The transpose of a matrix is usually denoted by $A^{\mathrm{T}}$; if $B$ = $A^{\mathrm{T}}$,
then for any $i$ and $j$, $b_{ij}$ = $a_{ji}$. Therefore, the transpose in [(2.3.2)](#232) is an n × m matrix:<br>
##### **(2.3.3)**
![Transpose matrix representation](../images/picture2_3_3.png)<br>

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

As a special type of matrix, a symmetric matrix $A$ is equal to its transpose: $A$ = $A^{\mathrm{T}}$. Here, we define a symmetric matrix $B$:

In [9]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

## **2.3.4 Tensor**
A tensor (in this subsection,
the term ‘tensor’ refers to an algebraic object) is a generalized way of describing an n-dimensional array with an arbitrary number of axes.

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## **2.3.5 Basic Properties of Tensor Algorithms**
Scalars, vectors, matrices and tensors with any number of axes (the term ‘tensor’ in this subsection refers to algebraic objects) possess a number of practical properties. For example, from the definition of
element-wise operations, it can be seen that **any unary element-wise operation does not alter the shape of its operands. Similarly, given any two tensors of the same
shape, the result of any binary element-wise operation will be a tensor of the same shape**. For example, adding two matrices of the same shape
involves performing element-wise addition on these two matrices.

In [11]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

**More specifically, the element-wise multiplication of two matrices is known as the Hadamard product (symbol ⊙)**. For a matrix $B$ ∈ $\mathbb{R}^{m×n}$,
where the element at row $i$ and column $j$ is $b_{ij}$. The Hadamard product of matrices $A$ (defined in [(2.3.2)](#232) and $B$ is:<br>
##### **(2.3.4)**
![Hadamard product](../images/picture2_3_4.png)

In [12]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

**Multiplying or adding a scalar to a tensor does not alter the tensor’s shape; each element of the tensor is added to or multiplied by the scalar.**

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## **2.3.6 Dimension Reduction**
A useful operation on any tensor is to compute the sum of its elements. In mathematical notation, the summation is represented by a symbol $\sum$.

In [14]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

We can denote the sum of the elements of a tensor of arbitrary shape. For example, the sum of the elements in matrix A can be written as $\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}$.

In [15]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

**By default, calling the sum function reduces the dimension of a tensor along all axes, turning it into a scalar.** We can also specify along which
axis the tensor should be reduced in dimension through summation. Taking a matrix as an example, to reduce the dimension by summing the elements of all rows (axis 0), you can specify
`axis=0` when calling the function. Since the input matrix is reduced in dimension along axis 0 to produce an output vector, the dimension along axis 0 of the input disappears in the output shape.

In [16]:
A_sum_axis0 = A.sum(dim=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

Specifying `axis=1` reduces the dimensionality by aggregating the elements of all columns (axis 1). Therefore, the dimension of input axis 1 is lost in the output shape.

In [17]:
A_sum_axis1 = A.sum(dim=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

**Summing a matrix row by row and column by column is equivalent to summing all of its elements.**

In [18]:
A.sum(dim=[0, 1])

tensor(190.)

A quantity related to summation is the mean (or average). We calculate the mean by dividing the sum by the total number of elements. In code,
we can call a function to calculate the mean of a tensor of any shape.

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

Similarly, a function that computes the average can also reduce the dimension of a tensor along a specified axis.

In [20]:
A.mean(dim=0), A.sum(dim=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

### Non-dimension-reduction summation

Sometimes it can be helpful to keep the number of axes constant when calling a function to calculate a sum or an average.

In [26]:
sum_A = A.sum(dim=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

Since `sum_A` still has two axes after summing each row, we can use broadcasting to divide `A` by `sum_A`.

In [27]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

If we want to compute the cumulative sum of element A along a specific axis—for example, axis=0 (computed by row)—we can call the `cumsum` function. This function does not reduce the dimension of the input tensor along
any axis.

In [28]:
A.cumsum(dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## **2.3.7 Dot Production**
Another of the most fundamental operations is the dot product. Given two vectors **x** and **y** ∈ $\mathbb{R}^{d}$, their
dot product $x^{⊤}$**y** (or ⟨**x**,**y**⟩) is the sum of the element-wise products at corresponding positions: **x**$^⊤$**y** = $\sum^{d}
_{i=1}x_{i}y_{i}$.

In [29]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

Note that we can **represent the dot product of two vectors by performing element-wise multiplication and then summing the results**:

In [30]:
torch.sum(x * y)

tensor(6.)

## **2.3.8 Matrix-Vector Product**
Recall the matrix $A \in \mathbb{R}^{m \times n}$ and the vector $x \in \mathbb{R}^{n}$ defined in [(2.3.2)](#232) and
[(2.3.1)](#231), respectively. Let’s represent the matrix $A$ using its row vectors:<br>
##### (2.3.5)
![Row Vector Representation of a Matrix](../images/picture2_3_5.png)<br>
Each $a^{}⊤_{i}$ ∈ $\mathbb{R}^n$ is a row vector representing the i-th row of the matrix. The matrix-vector product $Ax$ is a column vector of length $m$, whose i-th element is the dot
product $a^{⊤}_{i}x$:<br>
##### (2.3.6)
![Matrix Calculation](../images/picture2_3_6.png)<br><br>
To represent matrix-vector multiplication using tensors in code, we use the `mv` function. When we call `torch.mv(A, x)` for matrix A and vector x, it performs
the matrix-vector multiplication. Note that the Levi dimension of A (its length along axis 1) must be the same as the dimension of x (its length).

In [31]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## **2.3.9 Matrix-Matrix Multiplication**
Suppose there are two matrices $A$ ∈ $\mathbb{R}^{(n×k)}$ and $B$ ∈ $\mathbb{R}^{(k×m)}$:<br>
##### (2.3.7)
![Matrices A and B](../images/picture2_3_7.png)<br>
The simplest way to compute the matrix product C = AB is to consider the row vectors of A and the column vectors of B:<br>
##### (2.3.8)
![Vector Representation of Matrices](../images/picture2_3_8.png)<br>
When we simply compute each element $c_{ij}$ as the dot product $a^{⊤}_{i}b_{j}$:
##### (2.3.9)
![Vector Representation of Matrices production](../images/picture2_3_8.png)<br>
We can view matrix-matrix multiplication $AB$ as simply performing m matrix-vector products and concatenating the results to form an $n×m$ matrix.

In [32]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## **2.3.10 Norm**
**Informally speaking, the norm of a vector indicates how large the vector is. The concept of “size” considered here
does not involve dimension, but rather the magnitude of the components.**<br><br>
**In linear algebra, a vector norm is a function $f$ that maps a vector to a scalar. For any given vector $x$, the vector norm must satisfy certain properties. The first
property is: if we scale all elements of the vector by a constant factor $\alpha$, its norm is also scaled by the absolute value of the same constant factor**:
##### (2.3.10)
$$f(\alpha x) = |\alpha|f(x)$$<br><br>
**The second property is the familiar triangle inequality**:<br>
##### (2.3.11)
$$f(x + y) \le f(x) + f(y)$$<br><br>
**The third property, simply put, is that the norm must be nonnegative**:
##### (2.3.12)
$$f(x) \ge 0$$<br><br>
This makes sense. In most cases, the smallest possible size of anything is 0. **The last property states that the norm is at its minimum—0—if and only if
the vector consists entirely of zeros**.
##### (2.3.13)
$$\forall i, [x]_{i} = 0 \Leftrightarrow f(x) = 0$$<br><br>
In fact, the Euclidean distance is an $L_2$ norm: Let x be an n-dimensional vector with elements $x_1$, ..., $x_n$. Its $L2$ norm is the square root of the sum of the squares of the vector’s elements:
##### (2.3.14)
$$||x||_{2} = \sqrt{\sum\limits_{i=1}^{n}x_{i}^{2}}$$<br><br>
In particular, the subscript 2 is often omitted in the $L2$ norm, meaning that ∥x∥ is equivalent to $||x||_{2}$. In code, we can calculate the $L_2$ norm of a vector as follows.

In [33]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In deep learning, the square of the $L_2$ norm is used more frequently, and **the $L_1$ norm is also commonly encountered; it is defined as the sum of the absolute values of the vector’s elements**:
##### (2.3.15)
$$||x||_{1} = \sum\limits_{i=1}^{n}|x_{i}|$$<br><br>
Compared to the $L_2$ norm, the $L_1$ norm is less sensitive to outliers. To compute the $L_1$ norm, we combine the absolute value function with element-wise summation.

In [34]:
torch.abs(u).sum()

tensor(7.)

Both the $L_2$ norm and the $L_1$ norm are special cases of the more general $L_p$ norm:
##### (2.3.16)
$$||x||_{p} = \left(\sqrt{\sum\limits_{i=1}^{n}|x_{i}^{p}|}\right)^{1/p}$$<br><br>
Similar to the $L_2$ norm of a vector, the Frobenius norm of a matrix $X \in \mathbb{R}^{m \times n}$ is the square root of the sum of the squares of its elements:
##### (2.3.17)
$$||x||_{F} = \sqrt{\sum\limits_{i=1}^{m}\sum\limits_{i=1}^{n}x_{ij}^{2}}$$<br><br>

In [35]:
torch.norm(torch.ones(4, 9))

tensor(6.)

### Norm and Goal
In deep learning, we often seek to solve optimization problems: maximizing the probability assigned to observed data; minimizing the
distance between predictions and actual observations. We represent items (such as words, products, or news articles) as vectors in order to minimize the distance between similar items and maximize the distance between
different items. The objective—perhaps the most important component of a deep learning algorithm (aside from the data)—is typically expressed as a norm.