# **2.1 Data Manipulation**
In order to carry out various data operations, we need a way to store and manipulate data. Generally speaking, there are two key tasks we need to perform: (1)
acquiring data; (2) processing the data once it has been read into the computer. If there were no way to store data, then acquiring it would be
pointless.<br><br>
First, we introduce n-dimensional arrays, also known as tensors. Readers who have used the NumPy computational package in Python will be very familiar with this section.
Regardless of which deep learning framework is used, its tensor class (ndarray in MXNet, and Tensor in PyTorch and TensorFlow) is
are similar to NumPy’s `ndarray`. However, deep learning frameworks offer some important features that NumPy’s `ndarray` lacks: **firstly, they provide excellent support for GPU-accelerated
computations, whereas NumPy only supports CPU computations; secondly, tensor classes support automatic differentiation.** These features make tensor classes better suited to deep learning. Unless
otherwise stated, the term ‘tensor’ as used in this book refers to instances of the tensor class.<br><br>
## 2.1.1 Getting Started
First, we import `torch`. Please note that although it is known as PyTorch, the code uses `torch` rather than `pytorch`. Here we use d2l package directly.

In [1]:
import torch

A tensor represents an array of numerical values, which may have multiple dimensions. A tensor with one axis corresponds to a mathematical vector;
a tensor with two axes corresponds to a mathematical matrix; tensors with more than two axes have no specific mathematical name.<br><br>
First, we can use `arange` to create a row vector `x`. This row vector contains the first 12 integers starting from 0; by default, these are created as integers.It is also possible to specify that they be created as floating-point numbers. Each value in a tensor is referred to as an element. For example, the tensor `x` has 12
elements. Unless otherwise specified, new tensors will be stored in memory and computed using CPU-based calculations.

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

You can access the shape of a tensor (its dimensions along each axis) via its `shape` attribute.

In [3]:
x.shape

torch.Size([12])

If you simply wish to know the total number of elements in a tensor—that is, the product of all elements in its shape—you can check its size. Since we are dealing with
a vector here, its shape is the same as its size.

In [4]:
x.numel()

12

To change the shape of a tensor without altering the number or values of its elements, you can call the `reshape` function. For example, you can convert the tensor `x` from a row vector of shape
(12, ) into a matrix of shape (3,4). This new tensor contains the same values as before the conversion, but it is treated as a matrix with 3 rows and 4 columns
. It is important to emphasize that, although the shape of the tensor has changed, its element values remain unchanged. Note that changing the shape of a tensor
does not alter its size.

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

We do not need to change the shape by manually specifying each dimension. In other words, if our target shape is (height, width), then once
the width is known, the height is automatically calculated; we do not need to perform the division ourselves. In the example above, to obtain a matrix with 3 rows,
we manually specified that it has 3 rows and 4 columns. Fortunately, we can utilize this automatic dimension calculation feature by using -1. In other words, we can
use `x.reshape(-1, 4)` or `x.reshape(3, -1)` instead of `x.reshape(3, 4)`.<br><br>
Sometimes, we wish to initialize a matrix using all zeros, all ones, other constants, or numbers sampled at random from a specific distribution. We can create
a tensor of shape (2, 3, 4) in which all elements are set to 0. The code is as follows:

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Similarly, we can create a tensor of shape (2, 3, 4) in which all elements are set to 1. The code is as follows:

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Sometimes we wish to obtain the values of each element in a tensor by randomly sampling from a specific probability distribution. For example, when we construct arrays to serve
as parameters in a neural network, we usually initialize the parameter values randomly. The following code creates a tensor of shape (3, 4), in which
each element is randomly sampled from a standard Gaussian distribution (normal distribution) with a mean of 0 and a standard deviation of 1.

In [8]:
torch.randn(3, 4)

tensor([[ 1.1485,  1.1214,  0.1308,  1.0269],
        [-0.1085, -1.1768,  1.4753,  0.9523],
        [-1.6754,  0.9172,  0.6981, -0.8963]])

We can also assign specific values to each element of the desired tensor by providing a Python list (or nested list) containing numerical values. Here,
the outermost list corresponds to axis 0, whilst the inner lists correspond to axis 1.

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 Operators
For any two tensors of the same shape, the standard arithmetic operators (+, -, *, / and **) can all be extended to perform element-wise operations. We
can apply element-wise operations to any two tensors of the same shape.

In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

The ‘element-by-element’ approach allows for a wider range of computations, including unary operators such as raising to a power.

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

We can also concatenate multiple tensors, stacking them end-to-end to form a larger tensor. We simply
need to provide a list of tensors and specify along which axis to concatenate them.

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Sometimes, we wish to construct a binary tensor using logical operators. Take X == Y as an example: for each position, if X and Y are equal at that position, then the value of the corresponding element in the new
tensor is 1. This means that the logical statement X == Y is true at that position; otherwise, the value at that position is 0.

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Summing over all elements in a tensor produces a single-element tensor.

In [14]:
X.sum()

tensor(66.)

## 2.1.3 Broadcast mechanism
In some cases, even when the shapes differ,
we can still perform element-wise operations by utilizing the broadcasting mechanism. This mechanism works as
follows:<br><br>
**1. Expand one or both arrays by copying elements as necessary, so that after the transformation, the two tensors have the same shape;<br>**
**2. Perform the element-wise operation on the resulting arrays.**<br><br>
In most cases, we will **broadcast along the axis of the array that has a length of 1**, as in the following example:

In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

Since a and b are 3×1 and 1×2 matrices respectively, their shapes do not match if we were to add them together. We will broadcast both matrices into a larger
3×2 matrix, as shown below: matrix a will be duplicated column-wise, and matrix b will be duplicated row-wise, before they are added element-wise.

In [16]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 Indexing and Slicing
Elements in a tensor can be accessed via indices.As with any Python array: **the index of the first element
is 0, and the index of the last element is −1; you can specify a range to include the first element and all elements up to but not including the last one.**<br><br>
As shown below, we can use [-1] to select the last element, and [1:3] to select the second and third elements:

In [17]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

As well as reading from the matrix, we can also write elements to it by specifying an index.

In [18]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

**If we wish to assign the same value to multiple elements, we simply need to index all the elements and then assign the value to them.** For example, [0:2, :] accesses
the first and second rows, where ‘:’ represents all elements along axis 1 (columns). Although we are discussing matrix indexing, this also applies to vectors
and tensors with more than two dimensions.

In [19]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 Conserve memory
**Performing certain operations may result in memory being allocated for new results.**<br><br>
In the example below, we demonstrate this using Python’s `id()` function, which provides the exact memory address of the object being referenced. When
we execute `Y = Y + X`, we find that `id(Y)` points to a different location. **This is because Python first calculates `Y + X`, allocates new memory for the result,
and then sets `Y` to point to this new location in memory.**

In [20]:
before = id(Y)
Y = Y + X
id(Y) == before

False

This may not be advisable for two reasons:<br><br>
**1. Firstly, we do not want to allocate memory unnecessarily all the time. In machine learning, we may have hundreds of megabytes of parameters, and we update all of them multiple times per second.
Generally speaking, we want to perform these updates in-place;**<br><br>
**2. If we do not update in-place, other references will still point to the old memory locations, meaning that some of our code may inadvertently refer to the old parameters.**<br><br>
Fortunately, performing in-place operations is very straightforward. We can **use slice notation to assign the result of an operation to a previously allocated array**, for example, Y[:]
= <expression>. To illustrate this, we first create a new matrix Z with the same shape as Y, using `zeros_like` to
assign a block of all zeros.

In [21]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2393418226880
id(Z): 2393418226880


If X is not reused in subsequent calculations, we can also use X[:] = X + Y or X += Y to reduce the memory overhead of the operation.

In [22]:
before = id(X)
X += Y
id(X) == before

True

## 2.1.6 Convert to other Python objects
It is easy to convert tensors defined by deep learning frameworks into NumPy tensors (ndarray), and vice versa. **Torch tensors and NumPy arrays
share the same underlying memory, so in-place operations that modify one tensor will also modify the other.**

In [23]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

To convert a tensor of size 1 into a Python scalar, we can call the `item` function or use Python’s built-in functions.

In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)